generatorOptions:
  disableNameSuffixHash: true

resources:
  - manifests/golden-image-catalog.configmap.yaml
  - manifests/user-image-ui-schema.configmap.yaml

configMapGenerator:
  - name: admin-scripts
    files:
      - scripts/admin/validate_input.py
      - scripts/admin/validate_golden_input.py
      - scripts/admin/resolve_golden_image.py
      - scripts/admin/fetch_source.sh
      - scripts/admin/create_user_4_layer_dockerfile.sh
      - scripts/admin/create_golden_5_layer_dockerfile.sh
      - scripts/admin/build_and_push_image.sh
      - scripts/admin/write_result.sh
      - scripts/admin/write_golden_result.sh
